spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/tally
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
  data:
    redis:
      host: 127.0.0.1
      port: 6999
      password: 1234qwerZZ
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# 小程序信息
wx:
  app-id: wx10d0f0d0f0d0f0d0f0d0f0d0f0d0f0d
  app-secret: 9c3c0f0d0f0d0f0d0f0d0f0d0f0d0f0d

# 阿里云OSS配置
oss:
  endpoint: oss-cn-shanghai.aliyuncs.com  # OSS的访问域名
  accessKeyId: 123qwe123qwe123qwe123qwe123qwe       # 阿里云的Access Key ID
  accessKeySecret: 123qwe123qwe123qwe123qwe123qwe # 阿里云的Access Key Secret
  bucketName: test             # 存储桶名称
